import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../app/store';
import { string } from 'prop-types';
import FetchWatchlist from './watchlistAPI';

interface Stock {
  _id: string;
}

export interface WatchlistState {
  watchlist: Stock[];
  status?: 'idle' | 'loading' | 'failed';
}

const initialState: WatchlistState = {
  watchlist: [],
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchWatchlistAsync = createAsyncThunk(
  'watchlist/fetchWatchlist',
  async () => {
    const response = await FetchWatchlist();
    // The value we return becomes the `fulfilled` action payload
    return response.allStocks;
  }
);

const watchlistSlice = createSlice({
  name: 'watchlist',
  initialState,
  reducers: {
    setWatchlist: (state, action: PayloadAction<any>) => {
      state.watchlist = action.payload;
    },
    addStock: (state, action: PayloadAction<Stock>) => {
      state.watchlist.unshift(action.payload);
    },
    deleteStock: (state, action: PayloadAction<{ _id: string }>) => {
      alert('stock deleted');
      state.watchlist = state.watchlist.filter(
        (w) => w._id !== action.payload._id
      );
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchWatchlistAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchWatchlistAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.watchlist = action.payload;
      })
      .addCase(fetchWatchlistAsync.rejected, (state) => {
        state.status = 'failed';
      });
  },
});

export const selectWatchlist = (state: RootState) => state.watchlist.watchlist;

export const { setWatchlist, addStock, deleteStock } = watchlistSlice.actions;

export default watchlistSlice.reducer;
